# Generated by Django 4.1.5 on 2023-02-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ready_to_distribute',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=10),
        ),
    ]
